apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipeline-run-for-demo
spec:
  pipelineRef:
    name: pipeline-for-demo
  resources:
    - name: git-repo
      resourceRef:
        name: git-repo
    - name: image-registry
      resourceRef:
        name: image-registry
