apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-docker-image
spec:
  serviceAccountName: tutorial-service
  taskRef:
    name: build-docker-image-from-git-source
  params:
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: $(resources.inputs.docker-source.path)/examples/microservices/leeroy-web #configure: may change according to your source
  resources:
    inputs:
      - name: docker-source
        resourceRef:
          name: git-repo
    outputs:
      - name: builtImage
        resourceRef:
          name: image-registry

