apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image
spec:

  resources:
     inputs:
       - name: git-repo
         type: git
     outputs:
       - name: image-registry
         type: image
  params:
    - name: pathToDockerFile
      description: Path to Dockerfile
      default: Dockerfile
      type: string
    - name: pathToContext
      description: The build context used by Kaniko
      default: /workspace/git-repo/
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.10.0
      env:
        - name: "DOCKER_CONFIG"
          value: "/builder/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/workspace/git-repo/Dockerfile
        - --destination=srijaldocker/tekton:latest
        - --context=/workspace/git-repo/
      volumeMounts:
        - name: docker-config
          mountPath: /builder/home/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: docker-config
